# Generated by Django 6.1 on 2026-09-01 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='jogos/')),
                ('tipo_midia', models.CharField(choices=[('fisica', 'Física'), ('digital', 'Digital')], default='digital', max_length=10)),
                ('estoque', models.PositiveIntegerField(default=0)),
                ('categorias', models.ManyToManyField(related_name='jogos', to='jogos.categoria')),
                ('plataformas', models.ManyToManyField(related_name='jogos', to='jogos.plataforma')),
            ],
        ),
    ]
